@startuml gestion_biblioteca

title Diagrama de clases: Gestión Biblioteca

Class Autor {
    PK idAutor : Integer
    nombre : String
}


Class AutorLibro {
    PK FK idAutor : Integer
    PK FK ISBN : String
}


Class Bibliotecario {
    PK idBibliotecario : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : Date
    sexo : String
    fechaAlta : Date
    direccion : String
    telefono : String
    correoElectronico : String
}

Class Editorial {
    PK idEditorial : Integer
    nombre : String
}

Class Ejemplar {
    PK idEjemplar : Integer
    FK ISBN : String
    estadoConservacion : Enum {'muyMalo', 'malo', 'normal', 'bueno', 'muyBueno'}
    disponibleParaReserva : boolean
    enStock : boolean
}

Class Libro {
    PK ISBN : String
    FK idEditorial : Integer
    titulo : String
    descripcion : String
    idioma : String
    anioEdicion : String
    fechaPublicacion : Date
    encuadernacion : Enum {'tapaBlanda', 'tapaDura'}
    numPaginas : Integer
    genero1 : String
    genero2 : String
    enStock : boolean     
}

Class PeticionLibro {
    PK idPeticionLibro : Integer
    FK idUsuario : Integer
    FK ISBN : String
    ISBNLibroPedido : String
    
}

Class Reserva {
    PK idReserva : Integer
    FK idUsuario : Integer
    FK idEjemplar : Integer
    fechaHoraInicio : Datetime
    fechaHoraFin : Datetime
    fechaDevolucion : Datetime
    ejemplarPerdido : boolean
    ejemplarDeteriorado : boolean  
}

Class Sancion {
    PK idSancion : Integer
    FK idUsuario : Integer
    FK idBibliotecario : Integer
    motivo : String
    descripcion : String
}

Class Tema {
    PK idTema : Integer
    nombre : String
}

Class TemaLibro {
    PK FK idTema : Integer
    PK FK ISBN : String
}

Class Usuario {
    PK idUsuario : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : Date
    sexo : String
    fechaAlta : Date
    direccion : String
    telefono : String
    correoElectronico : String
}

Autor "1" -- "1..m" AutorLibro
AutorLibro "1..m" -- "1" Libro
Bibliotecario "1" .. "0..m" Sancion
Editorial "1" .. "1..m" Libro
Ejemplar "1..m" .. "1" Libro
Ejemplar "1" .. "0..m" Reserva
Libro "0..1" .. "0..m" PeticionLibro
Libro "1" -- "1..m" TemaLibro
PeticionLibro "0..m" .. "1" Usuario
Reserva "0..1" .. "1" Usuario
Sancion "0..m" .. "1" Usuario
Tema "1" -- "1..m" TemaLibro

@enduml