@startuml gestion_biblioteca

title Diagrama de clases: Gestión Biblioteca

Class Libro {
 PK ISBN : String
 FK idEditorial : Integer
 titulo : String
 descripcion : String
 idioma : String
 anioEdicion : String
 fechaPublicacion : Date
 encuadernacion : Enum {'tapaBlanda','tapaDura'} 
 numPaginas : Integer
 genero1 : String
 genero2 : String
 enStock : boolean  
    
}

Class AutorLibro {
    PK FK idAutor : Integer
    PK FK ISBN : String
}

Class Autor {
    PK idAutor : Integer
    nombre : String
    apellido : String
    fechaNacimiento : Date
    nacionalidad : String
}

Class Editorial {
    PK idEditorial : Integer
    nombre : String
    direccion : String
    telefono : String
    email : String
}

Class TemaLibro {
    PK FK idTema : Integer
    PK FK ISBN : String
}

Class Tema {
    PK idTema : Integer
    nombre : String
}

Class Bibliotecario {
    PK idBibliotecario : Integer
    nombre : String
    apellido : String
    fechaNacimiento : Date
    nacionalidad : String
    DNI : String
    sexo : String
    direccion : String
    telefono : String
    email : String
    fechaIngreso : Date
    fechaSalida : Date
}

Class Sancion {
    PK idSancion : Integer
    FK idBibliotecario : Integer
    FK idUsuario : Integer
    fechaInicio : Date
    fechaFin : Date
    motivo : String
    descripcion : String
}

Class PeticionLibro {
    PK idPeticionLibro : Integer
    FK idUsuario : Integer
    FK ISBN : String
    ISBNLibroPedido : String
    fechaPeticion : Date
    fechaEntrega : Date
    estado : Enum {'pendiente','aceptada','rechazada'}
    
}

Class Usuario {
    PK idUsuario : Integer
    nombre : String
    apellido : String
    fechaNacimiento : Date
    nacionalidad : String
    DNI : String
    sexo : String
    direccion : String
    telefono : String
    email : String
    fechaIngreso : Date
    fechaSalida : Date
    numPrestamos : Integer
    numPeticiones : Integer
    numSanciones : Integer
    numReservas : Integer
}

Class Ejemplar {
    PK idEjemplar : Integer
    FK ISBN : String
    estado : Enum {'muyMalo','malo','normal','bueno','muyBueno'}
    enStock : boolean
    disponibleParaReserva : boolean
}

Class Reserva {
    PK idReserva : Integer
    FK idUsuario : Integer
    FK idEjemplar : Integer
    fechaHoraInicio : Datetime
    fechaHoraFin : Datetime
    fechaDevolucion : Datetime
    ejemplarPerdido : boolean
    ejemplarDeteriorado : boolean
    
}

Libro "1" -- "1..m" AutorLibro
Libro "1" -- "1..m" TemaLibro
Libro "1" .. "1..m" Ejemplar
Libro "1..m" .. "1" Editorial
AutorLibro "1..m" -- "1" Autor
TemaLibro "1..m" -- "1" Tema
Bibliotecario "1" .. "0..m" Sancion
PeticionLibro "0..m" .. "0..1" Libro
Usuario "1" .. "0..m" Sancion
Usuario "1" .. "0..m" PeticionLibro
Usuario "1" .. "0..1" Reserva
Ejemplar "1" .. "0..m" Reserva




@enduml