@startuml IRs_horarios

title Requisitos Información: Horarios

Entity AlumnoClase {
    PK FK idEstudiante : Integer
    PK FK idEventoClase : Integer
}

Entity Estudiante {
    PK idEstudiante : Integer
    FK idHorario : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : String
    sexo : String
    fechaAlta : Date
    direccion: String
    telefono : String
    correoElectronico : String
    datosVerificados : Boolean
}

Entity EventoClase {
    PK idEventoClase : Integer
    nombreActividadAsignatura : String
    lugarAsignado : String
}

Entity Horario {
    PK idHorario : Integer
    curso : String
    grado : String
}

Entity HorarioEventoClase {
    PK FK idHorario : Integer
    PK FK EventoClase : Integer
    horaInicio : Datetime
    horaFin : Datetime
}

Entity PAS {
    PK idPAS : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : String
    sexo : String
    fechaAlta : Date
    direccion: String
    telefono : String
    correoElectronico : String
}

Entity PDI {
    PK idPDI : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : String
    sexo : String
    fechaAlta : Date
    direccion: String
    telefono : String
    correoElectronico : String
}

Entity PropuestaCambioHorario {
    PK idPropuestaCambio : Integer
    FK idPDI : Integer
    FK idHorario : Integer
    motivoProposicionCambio : String
    cambioPropuesto : String
}

AlumnoClase "0..m" -- "1" Estudiante
AlumnoClase "0..m" -- "1" EventoClase
Estudiante "0..m" .. "1" Horario
EventoClase "1" -- "0..m" HorarioEventoClase
Horario "1" -- "0..m" HorarioEventoClase
Horario "1" .. "0..m" PropuestaCambioHorario
PDI "1" .. "0..m" PropuestaCambioHorario

@enduml