@startuml gestion_biblioteca
title Gestión Biblioteca

Entity Autor {
    idAutor : String
}
Entity Bibliotecario {
    idBibliotecario : String
}
Entity Devuelve {
    idBibliotecario : String
    idEjemplar : String
    sancion : Double
}
Entity Editorial {
    idEditorial : String
}
Entity Ejemplar {
    idEjemplar : String
}
Entity EscritoPor {
    idAutor : String
    idLibro : String
}
Entity Libro {
    idLibro : String
}
Entity LibroCatalogado {
    idLibroCatalogado : String
}
Entity Pide {
    idLibro : String
    idUsuario : String
}
Entity Tema {
    idTema : String
}
Entity Trata {
    idLibro : String
    idTema : String
}
Entity Usuario {
    idUsuario : String
}

Autor "1..*" --- "1..*" Libro
(Autor, Libro) . EscritoPor

Bibliotecario "1..*" --- "1..*" Ejemplar
(Bibliotecario, Ejemplar) . Devuelve

Editorial "1" --- "1..*" Libro : lanza

Ejemplar "1..*" --- "1" LibroCatalogado : constituidoPor

Ejemplar "1..*" --- "1" Usuario : reserva

Libro <|--- LibroCatalogado

Libro "1..*" --- "1..*" Tema
(Libro, Tema) . Trata

Libro "1..*" --- "1..*" Usuario
(Libro, Usuario) . Pide

@enduml