@startuml compania_hostelera
title Compañia Hostelera

:Administrador: as A1
:Comun: as A2
:Comercial: as A3
:Cliente: as A4


(Recalcular precio) as UC1
(Bloquear temporalmente) as UC2
(Realizar oferta) as UC3
(Realizar oferta \n vista comercial) as UC4
(Gestionar nueva reserva) as UC5
(Gestionar nueva petición) as UC6
(Consultar reserva) as UC7
(Visualizar oferta) as UC8
(Consultar disponibilidad) as UC9
(Consultar) as UC10
(Buscar elemento) as UC11
(Mostrar un calendario) as UC12

A1 --> UC3
A1 --> UC6
A3 --> UC4
A3 --> UC5
A2 --> UC7
A4 --> UC8
A4 --> UC9

A2 <|-- A1
A2 <|-- A3
A4 <|-- A2
UC3 <|-- UC4
UC10 <|-- UC7
UC10 <|-- UC9

UC2 ..> UC4 : <<Extend>>

UC4 ..> UC1 : <<Include>>
UC10 ..> UC11 : <<Include>>
UC9 ..> UC12 : <<Include>>

@enduml