@startuml fotografia_online
title Fotografía Online

:Administrador: as A1
:Cliente: as A2
:Común: as A3
:Controlador: as A4
:Gestor: as A5
:Gestor de correo: as A6
:Software de facturación: as A7
:Vendedor: as A8

(Bloquear oferta) as UC1
(Buscar detalles \n en la foto)  as UC2
(Consultar foto) as UC3
(Crear email) as UC4
(Crear usuario) as UC5
(Denunciar foto) as UC6
(Editar factura) as UC7
(Editar información \n de foto) as UC8
(Editar usuario) as UC9
(Emitir factura) as UC10
usecase UC11 as "Hacer oferta a cliente

--
**extension points**
Reducir precio de producto"
(Indicar revisión de foto) as UC12
(Introducir \n explicación) as UC13
(Operaciones comunes \n de edición) as UC14
(Reducir precio \n de producto)  as UC15
(Ver oferta) as UC16
(Verificar datos \n introducidos) as UC17
usecase UC18 as "Visualizar foto

--
**extension points**
Denunciar foto"

A1 --> UC5
A1 --> UC9
A2 --> UC3
A2 --> UC18
A3 --> UC16
A4 --> UC8
A4 --> UC12
A5 --> UC1
A5 --> UC7
A5 --> UC10
A6 --> UC4
A7 --> UC10
A8 --> UC11
A8 --> UC2

A3 <|-- A2
A3 <|-- A5
A5 <|-- A1
UC12 <|-- UC6
UC14 <|-- UC7
UC14 <|-- UC9
UC18 <|-- UC2
UC18 <|-- UC3

UC6 ..> UC18 : <<Extend>>
UC15 ..> UC11 : <<Extend>>

UC2 ..> UC17 : <<Include>>
UC6 ..> UC13 : <<Include>>
UC12 ..> UC4 : <<Include>>

@enduml