@startuml horarios

title Horarios

:Estudiante: as A1
:PAS: as A2
:PDI: as A3

(Buscar en lista \n de clase) as UC1
(Consultar horario) as UC2
(Dar de alta estudiante) as UC3
usecase UC4 as "Dar de alta estudiante \n [vista PDI]

--
**extension points**
Buscar en lista de clase"
(Modificar horario) as UC5
(Proponer cambio de \n horario) as UC6
(Verificar datos) as UC7

A1 --> UC2
A2 --> UC3
A2 --> UC5
A3 --> UC4
A3 --> UC6

A1 <|-- A2
A1 <|-- A3
UC3 <|-- UC4

UC1 ..> UC4 : <<Extend>>

UC3 ..> UC7 : <<Include>>

@enduml