@startuml sistema_de_compras

title Sistema de Compras

:Administrador: as A1
:Comprador: as A2
:Proveedor: as A3
:Usuario: as A4
:Vendedor: as A5

(Acordar precio) as UC1
(Agregar producto)  as UC2
(Avisar)  as UC3
usecase UC4 as "Avisar de nuevo producto

--
**extension points**
Incorporar oferta"
(Avisar fin de oferta) as UC5
(Buscar producto) as UC6
(Consultar histórico \n de ventas) as UC7
(Consultar oferta) as UC8
(Consultar precio) as UC9
(Consultar producto) as UC10
(Eliminar oferta) as UC11
(Eliminar producto) as UC12
(Enviar notificación) as UC13
(Finalizar compra) as UC14
(Incorporar oferta) as UC15
(Marcar producto \n como bloqueado) as UC16
usecase UC17 as "Realizar venta

--
**extension points**
Consultar histórico de ventas"
(Verificar disponibilidad \n de producto) as UC18

A1 --> UC12
A2 --> UC2
A2 --> UC10
A2 --> UC14
A2 --> UC17
A3 --> UC4
A3 --> UC5
A4 --> UC8
A4 --> UC9
A5 --> UC17

A4 <|-- A1
A4 <|-- A2
A4 <|-- A3
A4 <|-- A5
UC3 <|-- UC4
UC3 <|-- UC5
UC6 <|-- UC10

UC7 ..> UC17 : <<Extend>>
UC15 ..> UC4 : <<Extend>>

UC2 ..> UC16 : <<Include>>
UC3 ..> UC13 : <<Include>>
UC5 ..> UC11 : <<Include>>
UC9 ..> UC6 : <<Include>>
UC10 ..> UC18 : <<Include>>
UC17 ..> UC1 : <<Include>>

@enduml