@startuml DC_sistema_de_compras

title Diagrama de clases: Sistema de Compras

Class Administrador {
    PK idAdministrador : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : Date
    sexo : String
    fechaAlta : Date
    direccion: String
    telefono : String
    correoElectronico : String
}

Class Aviso {
    PK idAviso : Integer
    FK idProveedor : Integer
    FK idProducto : Integer
    FK idOferta : Integer
    tipo : Enum {'nuevoProducto','finOferta'}
    motivo : String
    cuerpo : String
}

Class Carrito {
    PK idCarrito : Integer
    FK idComprador : Integer
}

Class Compra {
    PK idCompra : Integer
    FK idComprador : Integer
    FK idCarrito : Integer
    fecha : Date
}

Class Comprador {
    PK idComprador : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : Date
    sexo : String
    fechaAlta : Date
    direccion: String
    telefono : String
    correoElectronico : String
}

Class Notificacion {
    PK FK idAviso : Integer
    mensajeGenerado : String
}

Class Oferta {
    PK idOferta : Integer
    FK idProducto : Integer
    precioOriginal : Double
    precioNuevo : Double
    fechaInicio : Date
    fechaFin : Date
    vigente : Boolean
}

Class Producto {
    PK idProducto : Integer
    precio : Double
    bloqueado : Boolean
    disponible : Boolean   
}

Class ProductoEnCarrito {
    PK FK idProducto : Integer
    PK FK idCarrito : Integer
}

Class Proveedor {
    PK idProveedor : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : Date
    sexo : String
    fechaAlta : Date
    direccion: String
    telefono : String
    correoElectronico : String
}

Class Vendedor {
    PK idVendedor : Integer
    DNI : String
    nombreCompleto : String
    fechaNacimiento : Date
    sexo : String
    fechaAlta : Date
    direccion: String
    telefono : String
    correoElectronico : String  
}

Class Venta {
    PK idVenta : Integer
    FK idComprador : Integer
    FK idVendedor : Integer
    FK idProducto : Integer
    precioAcordado : Double
}

Aviso "1" --- "1" Notificacion
Aviso "0..1" ... "1" Oferta
Aviso "0..1" ... "1" Producto
Aviso "0..m" ... "1" Proveedor
Carrito "1" ... "0..1" Compra
Carrito "1" ... "1" Comprador
Carrito "1" --- "0..m" ProductoEnCarrito
Compra "0..m" ... "1" Comprador
Comprador "1" ... "0..m" Venta
Oferta "0..1" ... "1" Producto
Producto "1" --- "0..m" ProductoEnCarrito
Vendedor "1" ... "0..m" Venta

@enduml